// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// p_thirt_blockC
NumericMatrix p_thirt_blockC(int n_person, int n_dim, int block, int n_perm, int n_item, CharacterVector pair_names, CharacterVector perm_id, IntegerVector perm_item_vector, NumericVector params_gamma, NumericVector params_lambda, NumericVector params_psisq, NumericVector vector_theta, IntegerVector dict_item, IntegerVector dict_dim);
RcppExport SEXP _thirt_p_thirt_blockC(SEXP n_personSEXP, SEXP n_dimSEXP, SEXP blockSEXP, SEXP n_permSEXP, SEXP n_itemSEXP, SEXP pair_namesSEXP, SEXP perm_idSEXP, SEXP perm_item_vectorSEXP, SEXP params_gammaSEXP, SEXP params_lambdaSEXP, SEXP params_psisqSEXP, SEXP vector_thetaSEXP, SEXP dict_itemSEXP, SEXP dict_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_person(n_personSEXP);
    Rcpp::traits::input_parameter< int >::type n_dim(n_dimSEXP);
    Rcpp::traits::input_parameter< int >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type n_item(n_itemSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pair_names(pair_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type perm_id(perm_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type perm_item_vector(perm_item_vectorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params_gamma(params_gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params_lambda(params_lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params_psisq(params_psisqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector_theta(vector_thetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dict_item(dict_itemSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dict_dim(dict_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(p_thirt_blockC(n_person, n_dim, block, n_perm, n_item, pair_names, perm_id, perm_item_vector, params_gamma, params_lambda, params_psisq, vector_theta, dict_item, dict_dim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thirt_p_thirt_blockC", (DL_FUNC) &_thirt_p_thirt_blockC, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_thirt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
