# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_thirt_blockC <- function(n_person, n_dim, block, n_perm, n_item, pair_names, perm_id, perm_item_vector, params_gamma, params_lambda, params_psisq, vector_theta, dict_item, dict_dim) {
    .Call('_thirt_p_thirt_blockC', PACKAGE = 'thirt', n_person, n_dim, block, n_perm, n_item, pair_names, perm_id, perm_item_vector, params_gamma, params_lambda, params_psisq, vector_theta, dict_item, dict_dim)
}

